### ISSUE TITLE
Ruby rewrite

### ISSUE THREAD

**Issue by elifoster** [elifoster/GHULS#14]
I should rewrite the entire thing as Ruby code. This would involve creating a Ruby on Rails application, and a command line application.

**Comment by FayeAlephNil** [comment]
Sinatra would be better than Ruby on Rails

**Comment by elifoster** [comment]
Can you convince me f that? I think you might be right about drama-rb, because it's a very simple application, but I feel like due to GHULS complexity by nature would better suit rails.

**Comment by FayeAlephNil** [comment]
Sinatra just allows you to be more flexible, the rails style of doing things is very rigid. You can use all the same kinds of things with Sinatra, but you can do it in a much more lightweight and easy to manage fashion

**Comment by elifoster** [comment]
I have pretty much finished the CLI. Now all I need to get done is the web app.

@Strikingwolf I don't know, just by looking at examples I don't really like the syntax of Sinatra. I've read some stuff about it, and I am worried I'll end up just trying to recreate things that are already in Rails.

**Comment by FayeAlephNil** [comment]
Since rails is divided into plugins if you ended up doing that you could just use some of the rails gem plugins. I don't think this should really be a Rails project though _shrug_. Either way, mc drama generator should. Also there's an issue with mc drama gen currently, will post it there
