### ISSUE TITLE
Organizations not recognized correctly

### ISSUE THREAD

**Issue by thomas-daniels** [elifoster/GHULS#19]
http://ghuls.herokuapp.com/analyze?user=ProgramFOX says:

> Unfortunately, ProgramFOX has not contributed to any organizations :(.

But that's not correct (unless I'm misunderstanding "contributed" here), because I have contributed to open-source projects of organizations I'm in.

**Comment by elifoster** [comment]
I may need to rethink how it does it. Currently, it gets every repository in every organization that the user is in. Then it narrows it down by removing the ones that the user is not listed as a contributor for. I'm not really sure how else to do it without causing bloat; for example, I'm in a org with about 15 php repos, but I don't know the slightest bit of php.

**Comment by thomas-daniels** [comment]
I'm not familiar with the GitHub API, but I was wondering about this piece of code (utilities.rb):

```
is_collaborator = github.collaborator?(r[:full_name], username)
```

The description is:

> All the repository full names that the user has contributed to.

I'm not sure if the code and the description match, because collaborator != contributor: a collaborator is someone who has push access to a repo, and a contributor is someone who actually pushed commits to the repository.

However, if that's actually a bug, then I don't think it actually causes the original issue posted here, because it would cause to show more than it's supposed too, not less.

**Comment by elifoster** [comment]
Collaborators are more likely to actually have written a large portion of the code in the repository than a contributor. I miswrote "collaborator" as "contributor" in my prev post.

**Comment by thomas-daniels** [comment]
Hmm... interesting, when I run the CLI version myself I get correct data for the organizations; not sure why the web app doesn't display them.

**Comment by elifoster** [comment]
That's interesting. I'll look into that in like 30 minutes when I get on my computer. It should be getting identical data.

**Comment by elifoster** [comment]
I got the same result on both the cli and the web when analyzing you.

**Comment by thomas-daniels** [comment]
That's weird. I did get stats when using the CLI, but the Heroku app doesn't show anything.

**Comment by elifoster** [comment]
Can you show me what the CLI gave you?

**Comment by thomas-daniels** [comment]
Sure, here it is:

```
Getting language data for ProgramFOX...
JavaScript: 0.25%
Python: 27.75%
C#: 71.52%
Shell: 0.39%
Batchfile: 0.09%
Getting language data for their organizations...
JavaScript: 13.03%
HTML: 6.54%
PHP: 12.26%
Python: 15.91%
Ruby: 23.64%
CSS: 5.31%
CoffeeScript: 0.59%
Shell: 0.18%
C#: 21.86%
PLpgSQL: 0.4%
Smalltalk: 0.15%
PLSQL: 0.07%
PowerShell: 0.06%
```

**Comment by elifoster** [comment]
It might be because (I assume) you are logging in as yourself, so it is able to get more information for you? Try running it on me and post the results here. Although I doubt this is actually the problem.

**Comment by thomas-daniels** [comment]
Yeah, I was logging in as myself. Interestingly, when I logged in as myself but fetched your data, I did not get anything about orgs:

```
Getting language data for elifoster...
Ruby: 20.54%
CoffeeScript: 0.98%
HTML: 7.17%
CSS: 0.48%
Perl: 1.63%
Python: 1.68%
Java: 67.21%
Groovy: 0.31%
```

**Comment by elifoster** [comment]
I think a better way to do this would be, as you suggested, checking if they are a contributor to the repository. I just tried it, and got actually better data than with the old method. Ie, it was saying that my org data includes Rust code, even though I have never pushed to any of the Rust repos that I have push access to. It also worked when I analyzed you.

**Comment by elifoster** [comment]
Aaaand just tried on localhost, and actually got data about your organizations. Awesome.

**Comment by thomas-daniels** [comment]
Yay!

Yeah, indeed, it just came to my mind that you need to be actually in the organization to see who is a collaborator to a repo in the organization.

**Comment by elifoster** [comment]
It would have been nice if the docs for Octokit were a little more descriptive than "You need to be authenticated for this method" or whatever it says. Though I also should have actually read the GitHub API documentation :stuck_out_tongue:
