### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by elifoster** [elifoster/GHULS#22]
To let the user know that it is actually working, there should be a progress bar. I believe I would have to use JavaScript for the web application's progress bar, which is a bummer, but I know there are CLI progress bar gems. 
- [x] CLI
- [ ] Web

**Comment by elifoster** [comment]
I have done this for the CLI, but I'm not sure how to link the Ruby with JavaScript and HTML in order to properly create a progress bar. I need some sort of server-side handler that can link up to the JavaScript and HTML. I suppose I could force reload the page with the new data...

**Comment by elifoster** [comment]
Actually, I do not believe this is possible with how the app works. I could do it if I knew any amount of JavaScript, but alas, I do not.

**Comment by FayeAlephNil** [comment]
You should be able to do it with the inline ruby and html in ERB, although I'm not sure

**Comment by elifoster** [comment]
The only way I can think of doing it like that would be constantly reloading a new erb view, which is awful. It also doesn't even load the new page, for some reason.

**Comment by FayeAlephNil** [comment]
You can have dynamic variables in the ruby IIRC...

**Comment by elifoster** [comment]
Right but for it to actually show the progress of the work that is being done, it would need to constantly put the user into a new view.

**Comment by FayeAlephNil** [comment]
No you have a dynamically updating variable.

So you'd have a variable `progress` in Ruby, then you would display the progress bar using that variable. I don't see the problem...

**Comment by elifoster** [comment]
Would the variable update in the view?

**Comment by FayeAlephNil** [comment]
It should if I remember erb correctly

**Comment by elifoster** [comment]
Closing due to reorganization.
