### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by FayeAlephNil** [elifoster/GHULS#24]
I was wondering what you thought about separating the bulk of the code off into a separate gem, say ghuls-lib and thus people could use it as a library of it's own?

**Comment by elifoster** [comment]
I've been considering that. I've been considering making a ghuls organization with 3 repos: cli, web, and lib. It would be really easy to do. I could even then see if some of the Rubyists that I'm homies with (ie you, trajing, and xbony) were interested in helpin out with the development of them all. I'm still deciding on what to do, though.
