### ISSUE TITLE
Analyzing empty username?

### ISSUE THREAD

**Issue by thomas-daniels** [elifoster/GHULS#25]
http://ghuls.herokuapp.com/analyze

I have no idea what it analyzes, but... I guess it shouldn't, because no username is passed.

**Comment by FayeAlephNil** [comment]
Yeah santa you need to do a less general `get` construct in your main, I'll see what I can dig up in the sinatra docs

**Comment by FayeAlephNil** [comment]
You'll want to change the main `get '/analyze' do` block to two blocks. One `get '/analyze?user=:user' do |user|` and one `get '/analyze' do` after that to catch invalid formats on analyze

**Comment by elifoster** [comment]
Alright. I'll do that when I get up.

**Comment by elifoster** [comment]
Actually, I'm going to deal with this once #27 gets merged or closed, because I'm going to use the random user stuff for this.

`get '/analyze' do` will be for random things, and `get '/analyze?user=:user' do |user|` is going to be for set users.

**Comment by FayeAlephNil** [comment]
When this is sent you should redirect it to the regular `/analyze?user=<username>` that way it will save the result easily and be in browser history

**Comment by FayeAlephNil** [comment]
The example code for sinatra redirect is

```
get '/foo' do
  redirect to('/bar')
end

get '/bar' do
  do_something
  Optional: redirect back
end
```

**Comment by elifoster** [comment]
Yeah, that would be a much better way to do it lmao.

**Comment by FayeAlephNil** [comment]
Also, every now and then this generates an internal server error, may want to check the heroku logs and see what is up

**Comment by elifoster** [comment]
I believe that's just because it exceeds the rate limit. I meant to make an issue about it, but I actually just have absolutely no idea how to deal with that, aside from making people authenticate with the app, which is annoying and overly complex for this app.
