### ISSUE TITLE
Code Bloat and misleading data

### ISSUE THREAD

**Issue by FayeAlephNil** [elifoster/GHULS#28]
Something I've noticed while looking at some different analyzations is that code bloat from languages such as Java (where LOC per action is higher than say Ruby or something else) cause the graph to be skewed in their favor. I would propose having a weighted graph along with the non-weighted one which balances out the languages using some "expressivity factor", I'm not sure if you would have to come up with these yourself or if there may be some real comparison site you can use, but it would be a nice feature to add.

**Comment by elifoster** [comment]
Closing due to reorganization.
